version: '3.8'
services:
  backend:
    build:
      context: ./DP.Backend
      dockerfile: Dockerfile
    ports:
      - "5000:80"

  frontend:
    build:
      context: ./DP.Web
      dockerfile: Dockerfile
    ports:
      - "4200:80"