// <auto-generated />
using System;
using EatMyFat.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EatMyFat.Api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220315175951_AddMeasurement")]
    partial class AddMeasurement
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.14");

            modelBuilder.Entity("EatMyFat.Api.Models.Measurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Belly")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BicepsLeft")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BicepsRight")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CalfLeft")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CalfRight")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Chest")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ForearmLeft")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ForearmRight")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ThighLeft")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ThighRight")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Waist")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("EatMyFat.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BarCode")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Calories")
                        .HasColumnType("REAL");

                    b.Property<float?>("Carbohydrates")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<float?>("Fats")
                        .HasColumnType("REAL");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<float?>("Proteins")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
